### ISSUE TITLE
去除 inline-block 元素之间的留白间距

### ISSUE THREAD

**Issue by byodian** [byodian/blog#1]
-  行内元素垂直对齐时, 默认值为 `baseline` . 而行内替换元素, 比如 `<img>` 就是位于基线上, 因此它与文字或者空白符垂直对齐时, 图片下面会产生一个空白的间距.

![](https://raw.githubusercontent.com/byodian/logpic/master/gap.png)

- 浏览器会将 HTML 中的换行符、制表符、空白符合并成空白符，inline-block 元素水平布局时，换行符或空格分隔的情况下会出现一个空白符间距。

HTML 和 CSS 代码如下
```html
<ul>
  <li>Home</li>
  <li>Price</li>
</ul>
```

```css
li {
  display: inline-block;
  padding: 20px;
  background-color: pink;
}
```

结果:
![](https://raw.githubusercontent.com/byodian/logpic/master/1gap.png)

## 参考链接
[去除inline-block元素间间距的N种方法](https://www.zhangxinxu.com/wordpress/2012/04/inline-block-space-remove-%E5%8E%BB%E9%99%A4%E9%97%B4%E8%B7%9D/)
