### ISSUE TITLE
嵌入式对象自适应方案

### ISSUE THREAD

**Issue by byodian** [byodian/blog#12]

**Comment by byodian** [comment]
## 可伸缩的嵌入式图片和其他媒体对象

### 具有固定宽高比的图片的可伸缩设计

图片本身具有像素高度和宽度，且具有固定的宽高比，所以在响应式设计中给图片设置一个百分比数值宽度，高度设置为 auto , 这样图片就可以保持自适应。

```html
<div>
    <img src="../img/img.png">
</div>

img {
  width: 100%;
  height: auto;
}
```

但是， 图片的 width 设置为 100%，随着其容器尺寸的增大，它就会超出其固有的尺寸。这个问题可以通过将  max-width 设置为 100% 解决。

```html
<div>
    <img src="../img/img.png">
</div>

img {
  max-width: 100%;
  height: auto;
}
```

这里通过设置 max-width  属性为 100% 让元素变得可伸缩，同时又不会超出其固有大小。 

### 不具有固定宽高比容器的可伸缩性设计

比如 iframe 和  object 元素，就没有固定的宽高比。

```html
<iframe class="wrapper-iframe" width="916" height="515" src="https://www.youtube.com/embed/SMi6p8SKHK4" frameborder="0" allowfullscreen></iframe>

iframe {
  width; 100%;
  height: auto;
}
```

由于 iframe 没有固定的宽高比，在 iframe 元素上设置 width 为 100%, height 为 auto，将不会达到高度自适应的效果。

要解决这个问题，需要使用一些 CSS 技术，首先在 iframe 上包裹一个容器元素：

```html
<div class="resp-container">
    <iframe class="resp-iframe" width="916" height="515" src="https://www.youtube.com/embed/SMi6p8SKHK4" frameborder="0" ></iframe>
</div>
```

设置容器元素 CSS 代码如下： 

```css
.resp-container {
  // 宽度默认为父元素的 100%
  position: relative;
  padding-top: 56.25%;
  overflow: hidden;
}
```

- `position: relative` 可以作为子元素 iframe 定位的参考，因为在 CSS 中，设置为 `position: absolute` 的元素相对于它最近的  position  不为  static  的祖先元素来定位；
- `overflow:hidden` 隐藏溢出到容器外面的部分；
- `padding-top` 使用百分比数值设置 padding 可以确保容器有一个正确的宽高比，因为使用百分比数值设置 padding 其实际值基于包含块的宽度计算。此时，容器的宽度等于包含块的宽度，所以 padding-top 值实际值等于容器宽度的 56.25%。

设置 iframe 元素 CSS 代码如下： 

```css
.resp-iframe {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```

- `position: absolute` iframe 相对于 `position: relative` 的容器定位
- `top: 0` 和 `left: 0`: 将 iframe 定位到容器的中心
- `width: 100%` 和 `height: 100%`: iframe 的宽高等于容器的宽高，填满了整个容器。

这里有一种情况需要注意，如果不想使 iframe 包装容器的宽度为 100%，我们就的修改 padding-top 的值来确保容器的宽高比不变。但是我们不需要这么做，只要在容器的外面在添加一个包装元素，去设置最外面包装元素的宽度，即可实现灵活布局。

HTML 代码：

```html
<div class="wrapper">
  <div class="resp-container">
      <iframe class="resp-iframe" width="916" height="515" src="https://www.youtube.com/embed/SMi6p8SKHK4" frameborder="0" ></iframe>
  </div>
</div>
```

CSS 代码：

```css
.wrapper {
  width: 85%;
}

.resp-container {
  // 宽度默认为父元素的 100%
  position: relative;
  padding-top: 56.25%;
  overflow: hidden;
}

.resp-iframe {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```

## object-fit 属性
[TODO]

## 参考
- [Responsive Iframes with One Great CSS Trick](https://blog.theodo.com/2018/01/responsive-iframes-css-trick/)
