### ISSUE TITLE
CSS 存在的几套不同的规则

### ISSUE THREAD

**Issue by byodian** [byodian/blog#13]
- 格式化上下文
  - 行内格式化上下文
  - 块级格式化上下文
- 堆叠上下文

### Block formatting contexts
> It's the region in which the layout of block boxes occurs and in which floats interact with other elements.

它是块级盒子布局过程产生，也是浮动元素与其他元素交互的区域。

> Block formatting contexts are important for the positioning (see float) and clearing (see clear) of floats. The rules for positioning and clearing of floats apply only to things within the same block formatting context. Floats don't affect the layout of the content inside other block formatting contexts and clear only clears past floats in the same block formatting context. Margin collapsing also occurs only between blocks that belong to the same block formatting context.

BFC 对于浮动元素的定位和清除是重要的。浮动元素的定位和清除仅仅应用于同一个 BFC 元素。浮动元素不会影响其他具有 BFC 元素的布局，清除浮动也只应用在同一 BFC 元素中之前浮动的元素。外边距合并也只发生在同一 BFC 元素中。

### BFC 特性
- 一个块级格式化上下文的元素会包含它内部所有的后代元素 
- 不同的 BFC 元素之间不会发生折叠
- 具有 BFC 的元素可消除浮动元素的影响。 (忽略自己的边界必须接触自己的包含块边界的规则，此时该元素会收缩到适当大小)
- 具有 BFC 特性的元素，其内部的子元素无论怎么布局都不会影响到外面元素的布局和定位，也不会受到外面元素的影响，其表现就像一个独立封闭的容器，无论内部子元素如何定位布局，都不会干扰外面的元素。
- 实现更健壮和更智能的自适应布局。

#### 触发 BFC 条件

> Floats, absolutely positioned elements, block containers (such as inline-blocks, table-cells, and table-captions) that ** are not blocked boxes,** and block boxes with 'overflow' other than 'visible' (except when that value has been propagated to the viewport) **establish new block formatting contexts for their contents.**

- 根元素（`<html>`）
- `float` 值不为 none
- `position` 值不为 relative 和 static
- `overflow` 值为 auto、hidden 或者 scroll
- `table` 和 `table captions` 元素
- `display` 的值为 inline-block 的元素
- `display` 的值为 table、table-cell、table-row、table-caption、table-row-group、table-header、table-footer-group 的匿名 table 元素
- `display` 值为 flow-root
- Flex items
- Grid items

### 举例

浮动元素和 BFC 元素实现自动填充的自适应布局。

HTML 代码
```html
    <div class="media-container">
      <img class="media-picture" src="xx.png" >
      <div class="media-body">
        <h3>Title</h3>
        <p>Description</p>
      </div>
    </div>
```
CSS 代码
```css
    /* .media-container 元素避免高度塌陷, 具有 BFC 特性的元素会包含所有的子元素*/
    /* .media-body clear float */
    .media-container, .media-body {
    	overflow: hidden;
    }
    
    .media-picture {
    	float: float;
    	margin-right: 10px;
    }
```
### Relative positioning
