### ISSUE TITLE
如何使 inline-block 水平或者 block-level 水平元素的高度是父级元素的 100%？

### ISSUE THREAD

**Issue by byodian** [byodian/blog#42]
**绝对定位的宽高比计算是相对于 padding-box 的，而非绝对定位元素则是相对于 content-box 计算。**

[Demo](https://codepen.io/byodian/pen/xxbEzpr?editors=0110)
[参考](https://www.geeksforgeeks.org/how-to-make-flexbox-children-100-height-of-their-parent-using-css/)

使 inline-block level 或者 block-level 的元素 100% 高度生效的方法：

1. html, body 元素设置 `height: 100%`
```css
html, body {
  height: 100%;
}

/**/
.element {
  height: 100%;
}
```
2. 父元素设置一个具体高度，子元素使用 `height: 100%`
```css
.parent {
  height: 300px;
}

.child {
  height: 100%;
}
```
3. 使用绝对定位 `absolute`，父级元素不需要设置具体的 `height` 值，也可以生效。

```css
.child {
  position: absolute;
  height: 100%;
}
```

4. 某元素的父级元素为 flex box，且该元素在纵轴方向上对齐方式为 `stretch` 

```css
.flex-parent {
  display: flex;
  align-items: stretch;
  height: 200px;
  background-color: red;
}
```

5. 某元素的父级元素为 flex box，该元素在纵轴方向上对齐方式为 `flex-start`, `flex-end` 或者 `center`, `stretch` 除外，且设置元素 `height: 100%`

```css
.flex-parent {
  display: flex;
  align-items: flex-start;
  height: 200px;
  background-color: red;
}

.flex-child {
  height: 100%;
}
```
